import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// urlからデータを読み込む
fetch("https://zipcloud.ibsnet.co.jp/api/search?zipcode=7708072")
  // データを受け取って加工する（整形）
  .then((response) => {
    // .jsonと書くことで，連想配列に変換する
    return response.json();
  })
  .then((data) => {
    console.log(data);
  })
  // 通信にエラーが発生した場合errorを吐き出す。
  .catch((error) => {
    console.log(error);
  });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Population App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Population Graph</a>
        </h1>
        <h2>都道府県</h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
